config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:index] do
    resources :clients do
      resources :contacts, except: [:index, :show]
      resources :comments, only: [:new, :create]
    end
  end

  root to: 'sessions#index'
  get 'login', to: 'sessions#login', as: :login
  post 'authenticate', to: 'sessions#authenticate', as: :authenticate
  get 'logout', to: 'sessions#logout', as: :logout
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  validates :company_name, :value, :user, presence: true
  validates :value, numericality: { only_integer: true }
  validates :company_name, uniqueness: true

  belongs_to :user
  has_many :comments
  has_many :contacts
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, :client, presence: true

  belongs_to :client
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :role, :email, :phone, :client, presence: true
  validates :decision_maker, inclusion: { in: [true, false] }

  belongs_to :client
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, :last_name, :company, :email, :password_digest, presence: true
  validates :password_digest, length: { minimum: 6 }
  validates :email, uniqueness: true

  has_many :clients
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def index
    user = User.find_by(id: session[:user_id])
    @clients = user.clients
  end

  def new
    @client = Client.new
    render layout: false
  end

  def create
    user = User.find_by(id: session[:user_id])
    @client = user.clients.new(client_params)

    if @client.save
      flash[:success] = 'Customer profile created.'
      redirect_to "/users/#{user.id}/clients/#{@client.id}", status: 200
    else
      flash[:info] = @client.errors.full_messages.first
      render 'new'
    end
  end

  def show
    user = User.find_by(id: session[:user_id])
    @client = user.clients.find_by(id: params[:id])
  end

  def edit
    user = User.find_by(id: session[:user_id])
    @client = user.clients.find_by(id: params[:id])
  end

  def update
    user = User.find_by(id: session[:user_id])
    @client = user.clients.find_by(id: params[:id])

    if @client.update_attributes(client_params)
      flash[:success] = 'Customer profile updated.'
      redirect_to @client
    else
      flash[:danger] = 'Unable to update profile.'
      render 'edit'
    end
  end

  def destroy
    user = User.find_by(id: session[:user_id])

    if @client = user.clients.find_by(id: params[:id])
      @client.destroy
      redirect_to user.clients
    end
  end

  private

  def client_params
    params.require(:client).permit(:company_name, :value)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    render layout: false
  end

  def create
    client = Client.find_by(id: params[:client_id])
    @comment = client.comments.new(comment_params)

    if @comment.save
      render partial: 'show', locals: {comment: @comment}
    else
      @errors = @comment.errors.full_messages
      render 'new', layout: false
    end
  end

  def show
    render layout: false
  end

  private

  def comment_params
    params.require(:comment).permit(:title, :body, :client)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
    render layout: false
  end

  def create
    client = Client.find_by(id: params[:client_id])
    @contact = client.contacts.new(contact_params)

    if @contact.save
      render partial: 'show', locals: {contact: @contact}
    else
      render 'new'
    end
  end

  def show
    render layout: false
  end

  def edit
    client = Client.find_by(id: params[:client_id])
    @contact = client.contacts.find_by(id: params[:id])
    render layout: false
  end

  def update
    client = Client.find_by(id: params[:client_id])
    @contact = client.contacts.find_by(id: params[:id])

    if @contact.update_attributes(contact_params)
      flash[:success] = 'Contact profile updated.'
      redirect_to "/users/#{client.user_id}/clients/#{client.id}"
    else
      flash[:danger] = 'Unable to update contact profile.'
      render 'edit'
    end
  end

  def destroy
    if @contact = Contact.find_by(id: params[:id])
      @contact.destroy
      redirect_to "/users/#{@contact.client.user.id}/clients/#{@contact.client.id}"
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :role, :email, :phone, :decision_maker)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
    @user = User.new
  end

  def authenticate
    if @user = User.find_by(email: params[:email]).try(:authenticate, params[:password])
      session[:user_id] = @user.id
      redirect_to "/users/#{@user.id}/clients"
    else
      flash[:danger] = 'Not a valid email or password.'
      render 'login'
    end
  end

  def logout
    session.clear
    redirect_to '/'
  end

  private

  def session_params
    params.permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Thanks for signing up, #{@user.first_name}!"
      redirect_to @user
    else
      flash[:info] = @user.errors.full_messages.first
      render 'new'
    end
  end

  def show
    @user = User.find_by(id: session[:user_id])
  end

  def edit
    @user = User.find_by(id: session[:user_id])
  end

  def update
    @user = User.find_by(id: session[:user_id])

    if @user.update_attributes(user_params)
      flash[:success] = 'Profile Updated'
      redirect_to @user
    else
      flash[:danger] = 'Unable to update profile.'
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :company, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/clients/edit.erb
<h1>Edit Client Profile Here</h1>

<%= form_for @client, url: { action: 'update' } do |f| %>
  <%= f.label 'Company Name' %>
  <%= f.text_field :company_name %>
  <br>
  <%= f.label 'Value' %>
  <%= f.number_field :value %>
  <%= f.hidden_field :user %>
  <br>
  <%= f.submit 'Save Changes' %>
<% end %>

app/views/clients/index.erb
<div class="index-container">
  <div class="title-heading">
    <h2>Clients</h2>
  </div>
  <div class="add-client-container">
    <div class="text-right">
      <%= link_to "Add Client", new_user_client_path, class: "btn btn-success btn-sm add-client-btn" %>
    </div>
  </div>
  <div class="clients-list">
    <div class="list-group">
      <div class="row">
        <div class="col">
          <h6>Account</h6>
        </div>
        <div class="col">
          <h6>Value</h6>
        </div>
        <div class="col">
          <h6>Decision Maker</h6>
        </div>
        <div class="col">
          <h6>Last Reached Out</h6>
        </div>
        <div class="col">
          <h6>Last Comment</h6>
        </div>
      </div>
      <% @clients.each do |client| %>
      <div class="list-group-item">
        <div class="row">
          <div class="col">
            <%= link_to client.company_name, [client.user, client] %>
          </div>
          <div class="col">
            <small><%= client.value %></small>
          </div>
          <div class="col">
            <% if client.contacts.where(decision_maker: true).blank?  %>
              <small>n/a</small>
            <% else %>
              <small><%= client.contacts.where(decision_maker: true).first.name %></small>
              <br>
              <small><%= client.contacts.where(decision_maker: true).first.role %></small>
            <% end %>
          </div>
          <div class="col">
            <% if client.comments.last == nil %>
              <small>n/a</small>
            <% else %>
              <small><%= client.comments.last.created_at.strftime("%b. %d %Y") %></small>
            <% end %>
          </div>
          <div class="col text-truncate">
            <% if client.comments.last == nil %>
              <small>n/a</small>
            <% else %>
              <small><%= client.comments.last.body %></small>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/clients/new.erb
<div class="new-client-container">
  <div class="close-client-new">
    <button type="button" class="justify-content-end close" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="new-client-form">
    <%= form_for @client, url: { action: 'create' } do |f| %>
    <div class="form-group">
      <%= f.label '', 'Company Name', class: 'small' %>
      <%= f.text_field :company_name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label '', 'Value', class: 'small' %>
      <%= f.number_field :value, class: 'form-control' %>
    </div>
    <%= f.hidden_field :user %>
    <%= f.submit 'Create Profile', id: 'client_submit', class: 'btn btn-primary btn-sm btn-block', disabled: true %>
    <% end %>
  </div>
</div>

app/views/clients/show.erb
<div class="title-heading">
  <h3><strong><%= @client.company_name %></strong></h3>
</div>
<div class="row contents-container">
  <div class="col">
    <div class="comments-container">
      <div class="row comments-header">
        <div class="col">
          <h4>Comments</h4>
        </div>
        <div class="col add-comment-container">
          <a id="add-comment-button" class="btn btn-success btn-sm" href="/users/<%= @client.user.id %>/clients/<%= @client.id %>/comments/new">New Comment</a>
        </div>
      </div>
      <div class="list-group comment-list">
        <% @client.comments.order(created_at: :desc).each do |comment| %>
          <%= render partial: 'comments/show', locals: {comment: comment} %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-8">
    <div class="contacts-container">
      <div class="row contacts-header">
        <div class="col">
          <h4>Name</h4>
        </div>
        <div class="col">
          <h4>Role</h4>
        </div>
        <div class="col">
          <h4>Email</h4>
        </div>
        <div class="col">
          <h4>Phone</h4>
        </div>
        <div class="col">
          <a id="add-contact-button" class="btn btn-success btn-sm" href="/users/<%= @client.user.id %>/clients/<%= @client.id %>/contacts/new">Add Contact</a>
        </div>
      </div>
      <div class="list-group contact-list">
        <% @client.contacts.order(created_at: :desc).each do |contact| %>
          <%= render partial: 'contacts/show', locals: {contact: contact} %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/_new.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

<%= form_for @comment, url: {action: 'create'} do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Add Comment' %>
<% end %>

app/views/comments/_show.erb
<div class="list-group-item">
  <div class="row">
    <div class="col-sm-7">
      <h6><%= comment.title %></h6>
    </div>
    <div class="col">
      <small><%= comment.created_at.strftime("%I:%M%P, %b. %d %Y") %></small>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <small><%= comment.body %></small>
    </div>
  </div>
</div>

app/views/comments/new.erb
<div class="new-comment-container">
  <div class="close-comment-new">
    <button type="button" class="justify-content-end close" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="new-comment-form">
    <%= form_for @comment, url: {action: 'create'} do |f| %>
    <div class="form-group">
      <%= f.label '', 'Title', class: 'small' %>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label '', 'Body*', class: 'small' %>
      <%= f.text_area :body, class: 'form-control', rows: 4 %>
    </div>
    <%= f.submit 'Add Comment', id: 'comment_submit', class: 'btn btn-primary btn-block btn-sm', disabled: true %>
    <% end %>
  </div>
  <% if @errors %>
  <ul>
    <% @errors.each do |error| %>
    <li><small><%= error %></small></li>
    <% end %>
  </ul>
  <% end %>
</div>

app/views/contacts/_show.erb
<div class="list-group-item contact-list-item">
  <div class="row contact-row">
    <div class="col">
      <small><%= contact.name %></small>
      <% if contact.decision_maker == true %>
        <small>(<strong>DM</strong>)</small>
      <% end %>
    </div>
    <div class="col">
      <small><%= contact.role %></small>
    </div>
    <div class="col">
      <small><a href="mailto:<%= contact.email %>"><%= contact.email %></a></small>
    </div>
    <div class="col">
      <small><%= contact.phone %></small>
    </div>
    <div class="col">
      <%= link_to "Edit", edit_user_client_contact_path(contact.client.user, contact.client, contact), class: 'edit-contact small' %>
      <small>|</small>
      <%= link_to "Delete", user_client_contact_path(contact.client.user, contact.client, contact), method: 'delete', class: 'small' %>
    </div>
  </div>
</div>

app/views/contacts/edit.erb
<div class="contact-edit-container">
  <div class="close-contact-edit">
    <button type="button" class="justify-content-end close" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <%= form_for @contact, url: { action: 'update'} do |f| %>
  <div class="form-group">
    <%= f.label '', 'Name*', class: 'small' %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label '', 'Role*', class: 'small' %>
    <%= f.text_field :role, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label '', 'Email*', class: 'small' %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label '', 'Phone*', class: 'small' %>
    <%= f.text_field :phone, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label '', 'Decision Maker*', class: 'small' %>
    <%= f.select(:decision_maker, [['No', false], ['Yes', true]], {}, {class: 'form-control'}) %>
  </div>
  <div class="form-group">
    <%= f.submit 'Save Changes', class: 'btn btn-primary btn-sm btn-block' %>
  </div>
  <% end %>
</div>

app/views/contacts/new.erb
<div class="new-contact-container">
  <div class="close-contact-new">
    <button type="button" class="justify-content-end close" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
  <div class="new-contact-form">
    <%= form_for @contact, url: { action: 'create'} do |f| %>
    <div class="form-group">
      <%= f.label '', 'Name*', class: 'small' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label '', 'Role*', class: 'small' %>
      <%= f.text_field :role, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label '', 'Email*', class: 'small' %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label '', 'Phone*', class: 'small' %>
      <%= f.text_field :phone, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label '', 'Decision Maker*', class: 'small' %>
      <%= f.select(:decision_maker, [['No', false], ['Yes', true]], {}, {class: 'form-control'}) %>
    </div>
    <%= f.submit 'Create Contact', id: 'contact_submit', class: 'btn btn-primary btn-sm btn-block', disabled: true %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsforce</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="apple-touch-icon" sizes="76x76" href="/assets/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/favicon-16x16.png">
    <link rel="manifest" href="/assets/manifest.json">
    <link rel="mask-icon" href="/assets/safari-pinned-tab.svg" color="#5bbad5">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light justify-content-between" style="background-color: #AFD0BF">
      <a class="navbar-brand" href="/">
        <img src="/assets/railsforce.png" alt="Railsforce" width="60">
      </a>
      <ul class="nav">
        <% if @current_user = User.find_by(id: session[:user_id]) %>
        <li class="nav-item">
          <a class="nav-link" href="/users/<%= @current_user.id %>/clients">Clients</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/<%= @current_user.id %>"><%= @current_user.first_name %> <%= @current_user.last_name %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/logout">Log Out</a>
        </li>
        <% else %>
        <li class="nav-item">
          <a class="nav-link" href="/#about">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/#products">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/#contact">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/users/new">Sign Up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/login">Log In</a>
        </li>
        <% end %>
      </ul>
    </nav>

    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/users/_edit.erb
<div class="edit-form-container">
  <div class="edit-form">
    <%= form_for @user, url: { action: 'update' } do |f| %>
    <div class="form-row">
      <div class="col">
        <%= f.label :first_name, class: 'small' %>
        <%= f.text_field :first_name, class: 'form-control' %>
      </div>
      <div class="col">
        <%= f.label :last_name, class: 'small' %>
        <%= f.text_field :last_name, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :company, class: 'small' %>
      <%= f.text_field :company, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :email, class: 'small' %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password, class: 'small' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, class: 'small' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.submit 'Save Changes', class: 'btn btn-success btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/new.erb
<div class="container signup-logo">
    <img src="/assets/railsforce.png" alt="railsforce">
</div>

<div class="signup-form-container">
  <div class="signup-form">
    <%= form_for @user, url: { action: 'create' } do |f| %>
    <div class="form-group">
      <%= f.label '', 'First Name', class: 'small' %>
      <%= f.text_field :first_name, placeholder: 'Jessica', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label '', 'Last Name', class: 'small' %>
      <%= f.text_field :last_name, placeholder: 'Jones', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label '', 'Company', class: 'small' %>
      <%= f.text_field :company, placeholder: 'Alias Investigations', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label '', 'Email', class: 'small' %>
      <%= f.email_field :email, placeholder: 'jessica.jones@ai.com', class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label '', 'Password', class: 'small' %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label '', 'Confirm Password', class: 'small' %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <%= f.submit 'Create Account', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.erb
<div class="edit-title">
  <h1>Profile</h1>
</div>
<div class="container">
  <%= render partial: 'edit' %>
</div>